dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install:
- npm install
jobs:
  include:
    - stage: lint
      script: npm run lint
notifications:
  email:
  - gemini.wind285@gmail.com